import {
  Download,
  Share2,
  FileText,
  Building2,
  CheckCircle2,
  AlertTriangle,
  Clock,
  MapPin,
  Layers,
  Users,
} from "lucide-react";
import { Button } from "./ui/button";

const projectData = {
  id: "PRJ-001",
  name: "Dubai Marina Tower Extension",
  client: "Emaar Properties",
  location: "Dubai Marina, Plot 345-789",
  area: "2,500 sqm",
  floors: "15",
  usage: "Mixed-Use",
  analysisDate: "November 13, 2025",
  engineer: "Ahmed Hassan",
};

const authorities = [
  { name: "Dubai Municipality", status: "required", color: "blue" },
  { name: "DEWA", status: "required", color: "emerald" },
  { name: "Civil Defence", status: "required", color: "red" },
  { name: "RTA", status: "optional", color: "violet" },
  { name: "Emaar Properties", status: "required", color: "amber" },
];

const modifications = [
  {
    parameter: "Fire Exit Width",
    current: "1.2m",
    required: "1.5m",
    severity: "high",
    authority: "Civil Defence",
    regulation: "DCD-LS-03",
  },
  {
    parameter: "Parking Slots",
    current: "45",
    required: "52",
    severity: "medium",
    authority: "Dubai Municipality",
    regulation: "DM-P-2019-08",
  },
  {
    parameter: "Green Space Ratio",
    current: "12%",
    required: "15%",
    severity: "low",
    authority: "Dubai Municipality",
    regulation: "DM-ENV-2020-12",
  },
  {
    parameter: "Emergency Staircase",
    current: "1",
    required: "2",
    severity: "high",
    authority: "Civil Defence",
    regulation: "DCD-HS-05",
  },
];

const timeline = [
  { phase: "Document Preparation", duration: "5-7 days", status: "current" },
  {
    phase: "Authority Submissions",
    duration: "10-15 days",
    status: "upcoming",
  },
  { phase: "Review & Approvals", duration: "20-25 days", status: "upcoming" },
  { phase: "Final NOC Collection", duration: "10-13 days", status: "upcoming" },
];

export function FeasibilityReportContent() {
  return (
    <div className="step-transition max-w-5xl mx-auto p-4 md:p-8 space-y-6 md:space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div>
          <h1 className="text-slate-900 mb-2">Feasibility Report</h1>
          <p className="text-slate-600 text-sm md:text-base">
            Comprehensive analysis and approval pathway
          </p>
        </div>
        <div className="flex gap-3">
          <Button
            variant="outline"
            className="flex items-center gap-2 flex-1 sm:flex-none"
          >
            <Share2 className="w-4 h-4" />
            <span className="hidden sm:inline">Share</span>
          </Button>
          <Button className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white flex items-center gap-2 flex-1 sm:flex-none">
            <Download className="w-4 h-4" />
            <span className="hidden sm:inline">Download PDF</span>
            <span className="sm:hidden">PDF</span>
          </Button>
        </div>
      </div>

      {/* Report Container */}
      <div className="bg-white rounded-3xl shadow-xl border border-slate-200">
        {/* Report Header */}
        <div className="bg-gradient-to-br from-blue-500 to-indigo-600 text-white p-8 rounded-t-3xl">
          <div className="flex items-start justify-between mb-6">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 bg-white/20 backdrop-blur rounded-2xl flex items-center justify-center">
                <FileText className="w-8 h-8" />
              </div>
              <div>
                <h2 className="mb-1">AI Feasibility Analysis Report</h2>
                <p className="text-sm text-blue-100">
                  Generated by Aerotive UAE AI System
                </p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-sm text-blue-100">Report ID</p>
              <p className="text-lg">{projectData.id}</p>
            </div>
          </div>

          <div className="grid grid-cols-4 gap-4 bg-white/10 backdrop-blur rounded-2xl p-4">
            <div>
              <p className="text-xs text-blue-100 mb-1">Analysis Date</p>
              <p className="text-sm">{projectData.analysisDate}</p>
            </div>
            <div>
              <p className="text-xs text-blue-100 mb-1">Reviewed By</p>
              <p className="text-sm">{projectData.engineer}</p>
            </div>
            <div>
              <p className="text-xs text-blue-100 mb-1">Processing Time</p>
              <p className="text-sm">2.3 seconds</p>
            </div>
            <div>
              <p className="text-xs text-blue-100 mb-1">Confidence</p>
              <p className="text-sm">97.8%</p>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-8 space-y-8">
          {/* Project Summary */}
          <div>
            <h3 className="text-slate-900 mb-4 flex items-center gap-2">
              <Building2 className="w-5 h-5 text-blue-600" />
              Project Summary
            </h3>
            <div className="grid grid-cols-2 gap-4 p-6 bg-slate-50 rounded-2xl">
              <div className="space-y-3">
                <div>
                  <p className="text-xs text-slate-500 mb-1">Project Name</p>
                  <p className="text-sm text-slate-900">{projectData.name}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 mb-1">
                    Client/Developer
                  </p>
                  <p className="text-sm text-slate-900 flex items-center gap-2">
                    <Users className="w-4 h-4 text-slate-400" />
                    {projectData.client}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 mb-1">Location</p>
                  <p className="text-sm text-slate-900 flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-slate-400" />
                    {projectData.location}
                  </p>
                </div>
              </div>
              <div className="space-y-3">
                <div>
                  <p className="text-xs text-slate-500 mb-1">Built-up Area</p>
                  <p className="text-sm text-slate-900 flex items-center gap-2">
                    <Layers className="w-4 h-4 text-slate-400" />
                    {projectData.area}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 mb-1">
                    Number of Floors
                  </p>
                  <p className="text-sm text-slate-900">{projectData.floors}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 mb-1">Building Usage</p>
                  <p className="text-sm text-slate-900">{projectData.usage}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Feasibility Verdict */}
          <div>
            <h3 className="text-slate-900 mb-4">Feasibility Verdict</h3>
            <div className="bg-gradient-to-br from-amber-50 to-orange-50 border-2 border-amber-200 rounded-2xl p-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-amber-500 rounded-2xl flex items-center justify-center">
                  <AlertTriangle className="w-6 h-6 text-white" />
                </div>
                <div className="flex-1">
                  <h4 className="text-slate-900 mb-2">
                    Conditionally Feasible - Modifications Required
                  </h4>
                  <p className="text-sm text-slate-700 leading-relaxed mb-4">
                    The project is feasible for approval but requires{" "}
                    <strong>4 parameter modifications</strong> to comply with
                    Dubai Municipality and Civil Defence regulations. With these
                    changes, the project can proceed through the standard
                    approval process.
                  </p>
                  <div className="flex items-center gap-4 text-sm">
                    <div className="flex items-center gap-2 text-slate-700">
                      <Clock className="w-4 h-4" />
                      <span>
                        Estimated Timeline: <strong>45-60 days</strong>
                      </span>
                    </div>
                    <div className="flex items-center gap-2 text-slate-700">
                      <span>
                        Success Probability: <strong>94%</strong>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Authorities Involved */}
          <div>
            <h3 className="text-slate-900 mb-4">Authorities Involved</h3>
            <div className="grid grid-cols-5 gap-3">
              {authorities.map((auth) => (
                <div
                  key={auth.name}
                  className={`p-4 rounded-2xl text-center border-2 ${
                    auth.status === "required"
                      ? `border-${auth.color}-200 bg-${auth.color}-50`
                      : "border-slate-200 bg-slate-50"
                  }`}
                >
                  <div
                    className={`w-10 h-10 rounded-xl bg-gradient-to-br from-${auth.color}-500 to-${auth.color}-600 mx-auto mb-2 flex items-center justify-center`}
                  >
                    <Building2 className="w-5 h-5 text-white" />
                  </div>
                  <p className="text-xs text-slate-900 mb-1">{auth.name}</p>
                  <span
                    className={`text-xs px-2 py-0.5 rounded-full ${
                      auth.status === "required"
                        ? "bg-blue-100 text-blue-700"
                        : "bg-slate-200 text-slate-600"
                    }`}
                  >
                    {auth.status}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Required Modifications */}
          <div>
            <h3 className="text-slate-900 mb-4">Required Modifications</h3>
            <div className="overflow-hidden rounded-2xl border border-slate-200">
              <table className="w-full">
                <thead className="bg-slate-50 border-b border-slate-200">
                  <tr>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Parameter
                    </th>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Current
                    </th>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Required
                    </th>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Authority
                    </th>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Regulation
                    </th>
                    <th className="text-left px-4 py-3 text-sm text-slate-600">
                      Priority
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {modifications.map((mod, index) => (
                    <tr key={index} className="hover:bg-slate-50">
                      <td className="px-4 py-3 text-sm text-slate-900">
                        {mod.parameter}
                      </td>
                      <td className="px-4 py-3 text-sm text-slate-600">
                        {mod.current}
                      </td>
                      <td className="px-4 py-3 text-sm text-slate-900">
                        {mod.required}
                      </td>
                      <td className="px-4 py-3 text-sm text-slate-600">
                        {mod.authority}
                      </td>
                      <td className="px-4 py-3 text-sm text-slate-600 font-mono text-xs">
                        {mod.regulation}
                      </td>
                      <td className="px-4 py-3">
                        <span
                          className={`text-xs px-2 py-1 rounded-full ${
                            mod.severity === "high"
                              ? "bg-red-50 text-red-600"
                              : mod.severity === "medium"
                              ? "bg-amber-50 text-amber-600"
                              : "bg-slate-100 text-slate-600"
                          }`}
                        >
                          {mod.severity}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Estimated Timeline */}
          <div>
            <h3 className="text-slate-900 mb-4">Estimated Approval Timeline</h3>
            <div className="space-y-3">
              {timeline.map((phase, index) => (
                <div
                  key={index}
                  className={`p-4 rounded-2xl border-2 ${
                    phase.status === "current"
                      ? "border-blue-200 bg-blue-50"
                      : "border-slate-200 bg-slate-50"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div
                        className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                          phase.status === "current"
                            ? "bg-blue-500 text-white"
                            : "bg-slate-200 text-slate-500"
                        }`}
                      >
                        {phase.status === "current" ? (
                          <Clock className="w-5 h-5" />
                        ) : (
                          index + 1
                        )}
                      </div>
                      <div>
                        <p className="text-sm text-slate-900">{phase.phase}</p>
                        <p className="text-xs text-slate-600">
                          {phase.duration}
                        </p>
                      </div>
                    </div>
                    {phase.status === "current" && (
                      <span className="text-xs px-3 py-1 bg-blue-500 text-white rounded-full">
                        In Progress
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 p-4 bg-gradient-to-r from-emerald-50 to-teal-50 border border-emerald-200 rounded-2xl">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-600" />
                <div>
                  <p className="text-sm text-slate-900">
                    Total Estimated Duration
                  </p>
                  <p className="text-xs text-slate-600">
                    45-60 working days from submission to final approval
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Recommendations */}
          <div>
            <h3 className="text-slate-900 mb-4">AI Recommendations</h3>
            <div className="space-y-3">
              <div className="p-4 bg-blue-50 rounded-xl border border-blue-200">
                <p className="text-sm text-slate-900 mb-2">
                  🏗️ <strong>Priority Actions</strong>
                </p>
                <p className="text-sm text-slate-700">
                  Address high-severity modifications first (Fire Exit Width and
                  Emergency Staircase) as these are critical for Civil Defence
                  approval and cannot be waived.
                </p>
              </div>
              <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200">
                <p className="text-sm text-slate-900 mb-2">
                  💡 <strong>Optimization Opportunity</strong>
                </p>
                <p className="text-sm text-slate-700">
                  Consider submitting DEWA and RTA applications in parallel with
                  DM submission to reduce overall timeline by approximately
                  10-15 days.
                </p>
              </div>
              <div className="p-4 bg-amber-50 rounded-xl border border-amber-200">
                <p className="text-sm text-slate-900 mb-2">
                  ⚠️ <strong>Potential Risk</strong>
                </p>
                <p className="text-sm text-slate-700">
                  Emaar Properties design approval may require additional
                  iterations for façade materials. Recommend early consultation
                  with Emaar design team.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Report Footer */}
        <div className="border-t border-slate-200 p-6 bg-slate-50 rounded-b-3xl">
          <div className="flex items-center justify-between text-sm text-slate-600">
            <p>Report generated by Aerotive UAE AI © 2025</p>
            <p>Confidence Score: 97.8%</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export function FeasibilityReport() {
  return <FeasibilityReportContent />;
}
